### ISSUE TITLE
Add support for more dependency managers

### ISSUE THREAD

**Issue by spinach** [algolia/instantsearch-ios#10]
Right now we only support CocoaPods, and the main reason was because of this:

> InstantSearch Core has an external dependency (on the Algolia Search API Client). A package manager is therefore required to draw that dependency. Cocoapods works by adding special build phases to the Xcode project (in addition to creating a Pods project and an Xcode workspace referencing both). Because of this, it is technically impossible to support both Cocoapods and Carthage on the same project when it has external dependencies. Because Cocoapods has a wider audience than Carthage, we chose the former.

However, there are workarounds and we should add support for Carthage and SwiftPM

**Comment by sirvon** [comment]
+1 really want to use this! I only use carthage and manual integrations. any eta on how to plug this in without cocoapods reliance?

thanks!

**Comment by spinach** [comment]
Hi @sirvon - Thank you for your feedback! This is the first task on our todo. I will let you know as soon as we have support for new dependency managers. We'll need to do some modification to the 2 dependencies of InstantSearch. Hopefully the coming week :)

**Comment by spinach** [comment]
We now support Carthage as of version 1.0.1 🎉 . Check instructions [here](https://github.com/algolia/instantsearch-ios#carthage).

Thank you very much for your patience, and if you hit any problems, please do let us know!
