### ISSUE TITLE
Cannot build project in Xcode 12 with InstantSearch 7

### ISSUE THREAD

**Issue by scottiedog45** [algolia/instantsearch-ios#104]
**Describe the bug 🐛**
Project will not build- there seem to be errors in the source files. 

**To Reproduce 🔍**
Create new Xcode project. 
Add `pod 'InstantSearch', '~> 7.0'`
Try to build project

**Expected behavior 💭**
No build errors from source

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/31543854/88011223-caae5b80-cae4-11ea-8776-f7922a290977.png)

**Environment:**
 - OS: MacOS Catalina, 10.15.5
 - Xcode 12, beta 2

Thanks for looking into this! The `InstantSearchClient` is working fine for querying the algolia servers, but I'd like to use the `HitsInteractor` to parse the results.

**Comment by VladislavFitz** [comment]
Hello @scottiedog45 
Thank you for reporting this. I created a branch of Swift API Client containing the fixes of Xcode 12 compilation errors. 
To integrate it into your project, add this line to your Podfile:
```ruby
pod 'AlgoliaSearchClient', :git => 'https://github.com/algolia/algoliasearch-client-swift', :branch => 'feat/xcode12-support'
```
keeping the `pod 'InstantSearch', '~> 7.0.0'`. 
This must solve your problem.

**Comment by scottiedog45** [comment]
Hi @VladislavFitz -

Thanks for the quick response and action! Confirmed fixed. 

All best
