### ISSUE TITLE
Cannot declare hitsTableController

### ISSUE THREAD

**Issue by RuchirB** [algolia/instantsearch-ios#115]
**Describe the bug 🐛**
Upon following the [IOS](https://www.algolia.com/doc/guides/building-search-ui/getting-started/how-to/programmatically/ios/#before-we-start) tutorial detailing how to Display hits in a tableview, I am getting the error "'HitsTableController' is unavailable: Use your own UITableViewController conforming to HitsController protocol"

**To Reproduce 🔍**
Copy the line: 
`let hitsTableController: HitsTableController<HitsInteractor<JSON>> = .init(tableView: UITableView())`

from the above linked tutorial in XCode.

**Expected behavior 💭**
No Error

**Screenshots 🖥**
<img width="1040" alt="Screen Shot 2020-08-02 at 10 34 21 PM" src="https://user-images.githubusercontent.com/27583648/89149031-50cc9800-d510-11ea-8f12-97ec03f0b72d.png">

**Environment:**
 - OS: IOS Development on XCode

**Comment by VladislavFitz** [comment]
Hello @RuchirB 
Thank you for reporting this. 
The guide has been updated. Not it is compatible with the latest version of InstantSearch.
