### ISSUE TITLE
FacetListConnector should have a FacetListPresenter as an optional param

### ISSUE THREAD

**Issue by spinach** [algolia/instantsearch-ios#122]
We should add a convenient init for `FacetListConnector` to expose `FacetListPresenter`. 

In `FacetListConnector.swift` we do the following when connecting the interactor with the controller

```
interactor.connectController(controller)
```

We should add the optional presenter in the above method. 

Edit: Also, concerning the `selectionMode`, we should also be able to specify it without having to specify the `facets` param (can add a default value there)

**Comment by VladislavFitz** [comment]
The presenter seems to be [properly connected ](https://github.com/algolia/instantsearch-ios/blob/f1a7e71a78ef5f0e41aad3d6dc5f274c1b3ed33f/Sources/InstantSearchCore/FacetList/FacetListConnector.swift#L47) in the main FacetListConnector initializer if I got right your remark.

**Comment by VladislavFitz** [comment]
Added the default empty array values for `facets` in the #123
