### ISSUE TITLE
Objective-C Support

### ISSUE THREAD

**Issue by mustafa96m** [algolia/instantsearch-ios#125]
Hello Everyone,

Are there any plans to add objective-c support to InstantSearch 7. I believe there are many legacy projects out there that are already integrated with algolia (like us) or many more potentials that might want to integrate as well.

**Comment by VladislavFitz** [comment]
Hi @mustafa96m,

Unfortunately, the Objective-C support for InstantSearch is not on our roadmap.
 
I suggest you to use the [v. 7.0.5](https://github.com/algolia/algoliasearch-client-swift/releases/tag/7.0.5) of the Algolia Client which is compatible with Objective-C and to build your search experience on top of it.

**Comment by mustafa96m** [comment]
Thanks for the reply @VladislavFitz.

That what we are going for atm, can you please share 7.0.5 docs that include loading the facets and refinements etc.. so we can match the InstantSearch features.

**Comment by VladislavFitz** [comment]
Please find the documentation for the v7 [here](https://www.algolia.com/doc/deprecated/api-clients/swift/v7/methods/add-objects/)

The documentation about filtering can be found [here](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/).

Regarding the disjunctive faceting with facet count appearance, for some reason we don't provide a detailed guide. In brief,  you have to make multiple search requests and when merge their results into one result containing the correct faceting information.  
I suggest you to check the Swift implementation of [QueryBuilder](https://github.com/algolia/instantsearch-ios/blob/8c9ab5329bcf84b407a0e5beb3959d748046f9c5/Sources/InstantSearchCore/QueryBuilder/QueryBuilder.swift) and its [extension](https://github.com/algolia/instantsearch-ios/blob/8c9ab5329bcf84b407a0e5beb3959d748046f9c5/Sources/InstantSearchCore/QueryBuilder/QueryBuilder%2BDisjunctiveFaceting.swift) encapsulating the necessary logic. Then check how to use it for disjunctive faceting in the [SingleIndexSearcher source code](https://github.com/algolia/instantsearch-ios/blob/7b4aa41c52d1d426ac8201d37f78250d412202a4/Sources/InstantSearchCore/Searcher/SingleIndex/SingleIndexSearcher.swift#L147).

I hope it will help with your implementation.
