### ISSUE TITLE
Impossible to directly modify query of IndexQueryState in the MultiIndexSearcher 

### ISSUE THREAD

**Issue by VladislavFitz** [algolia/instantsearch-ios#127]
**Describe the bug 🐛**

Since `Query` became a structure  in the v8 of the Swift Client, it is now impossible to directly change the Query of `indexQueryStates` in the `MultiIndexSearcher` 

**To Reproduce 🔍**

```swift
let searcher: MultiIndexSearcher
    
// Compiler error: Cannot assign to property: 'indexQueryStates' setter is inaccessible
searcher.indexQueryStates[0].query.filters = "brand:sony"
```

**Environment:**
 - Version 7.1.0

**Comment by JHovah** [comment]
Hi Vladislav,

Is there a temporary fix for this bug?

**Comment by VladislavFitz** [comment]
Hi @JHovah ,

I submitted the [fix](https://github.com/algolia/instantsearch-ios/pull/133). It will be released in soon. 
In the meantime you can use the branch `fix/multi-index-search-index-query-state-access` in your implementation.
