### ISSUE TITLE
 Unrecognized Selector Sent To Instance - Sequencer Class

### ISSUE THREAD

**Issue by RichieViscardi** [algolia/instantsearch-ios#128]
I am using InstantSearch MultiIndex components and I am getting a crash that occurs every now and then. App crashes and returns  "unrecognized selector sent to instance" error. I set a breakpoint and see that it ends up crashing in the dismissOperation(withSeqNo seqNo: Int) function in the Sequencer class. When not setting a breakpoint, I also get the following error:

Thread. 3: EXC_BAD_ACCESS (code=1, address=0x18) in the cancelOperation(withSeqNo seqNo: Int) function in the Sequencer class.

In the view controller, I am using a MultiIndexSearcher, MultiIndexSearchConnector, MultiIndexHitsInteractor, and a MultiIndexHitsController to perform the search. I have a search controller to handle user input. I eliminated everything else in the viewcontroller except these Instant Search Components

The crash only happens about 1 in 8 times. It will work as expected for a couple of builds, and then will crash with the above error every now in then.

I am using iOS 14. I can provide additional details if needed.

**Comment by VladislavFitz** [comment]
Hi @RichieViscardi,
Thanks for your feedback!

I would be grateful if you provide a stack trace of your crash and, if possible, a steps to reproduce it.

**Comment by RichieViscardi** [comment]
It doesn't happen every time, so it might be a little tricky to reproduce; however, here is the code that I am working with. The crash happens as soon as I click the tab to get to this view controller. I don't even have a chance to tap the Search Bar. Perhaps I am setting up the MultiIndex components incorrectly.


`


    let multiSearcher = MultiIndexSearcher(appID: "***", apiKey: "***", indexNames: ["myIndex1", "myIndex2"])

    lazy var multiSearchConnector = MultiIndexSearchConnector(searcher: multiSearcher, indexModules: [MultiIndexHitsConnector.IndexModule.init(indexName: "myIndex1"), MultiIndexHitsConnector.IndexModule.init(indexName: "myIndex2")], searchController: searchController, hitsController: multiHitsTableViewController)

    lazy var hitsInteractor: MultiIndexHitsInteractor = {
      let userHitsInteractor: HitsInteractor<JSON> = .init(infiniteScrolling: .off)
      let missionHitsInteractor: HitsInteractor<JSON> = .init(infiniteScrolling: .off)
      return .init(hitsInteractors: [userHitsInteractor, missionHitsInteractor])
    }()

    let multiHitsTableViewController: MultiHitsViewController = .init()




    override func viewDidLoad() {
        super.viewDidLoad()

        multiSearchConnector.connect()

        hitsInteractor.connectSearcher(multiSearcher)
        hitsInteractor.connectController(multiHitsTableViewController)

        multiSearcher.search()
        setupUI()
    }


    func setupUI() {
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.hidesNavigationBarDuringPresentation = false
        searchController.showsSearchResultsController = true
        searchController.automaticallyShowsCancelButton = true
        searchController.searchBar.delegate = self
    }



`


As I mentioned, the crash happens before tapping the search bar. So the multiHitsTableViewController is never being shown. I followed the docs to create that class (uses hitSource and JSON to get info for the tableview cells). I didn't post it above since it is crashing before the multiHitsTableViewController would be displayed. I will try and get a stack trace as well. Thanks!

**Comment by VladislavFitz** [comment]
Thanks for the provided snippet. I managed to detect the issue. 
A fix will arrive soon, I'll keep you informed.

**Comment by RichieViscardi** [comment]
Awesome, thank you!

**Comment by aldoj86** [comment]
Same probleme here, using InstantSearch SingleIndexSearcher components.
In my case, crashes occurs more frequently with a device with iOS 13 than an iOS14 one.

**Comment by VladislavFitz** [comment]
We have just released [v7.2.0](https://github.com/algolia/instantsearch-ios/releases/tag/7.2.0). 
This crush must be fixed. 
Let me know if you have any issue and thanks for your patience.
