### ISSUE TITLE
Possible Error With Xcode 12.3 and Instant Search 7.6

### ISSUE THREAD

**Issue by JHovah** [algolia/instantsearch-ios#151]
**Describe the bug 🐛**
There is a swift compiler error on Xcode 12.3 and InstantSearch 7.6. The error reads:
"Type 'Hit<T>' does not conform to protocol 'Geolocated'"

**To Reproduce 🔍**
Updated from InstantSearch 7.4 to 7.6 today. Xcode version was already 12.3 and functioning properly before the pod update. 
1. Try and build project.
2. Look at compile time errors.

**Expected behavior 💭**
Expecting the code to properly compile.

**Screenshots 🖥**

<img width="1669" alt="Screen Shot 2020-12-18 at 9 03 47 PM" src="https://user-images.githubusercontent.com/33099609/102679464-ba72d900-4175-11eb-9d67-2aa4bff8b83e.png">

<img width="1680" alt="Screen Shot 2020-12-18 at 9 05 32 PM" src="https://user-images.githubusercontent.com/33099609/102679474-ca8ab880-4175-11eb-89c4-019f7ad179db.png">

**Environment:**
Mac - Big Surr
Version - 11.01

**Additional context**
Downloaded InstantSearch Project to test if project itself was the problem, but the instant search project shows the same error.

**Comment by VladislavFitz** [comment]
Hi @JHovah,
Thank you for reporting this. A patch fixing this issue is in progress.

**Comment by VladislavFitz** [comment]
The issue has been fixed ✅
