### ISSUE TITLE
Compiler error Xcode 12

### ISSUE THREAD

**Issue by ferrlan** [algolia/instantsearch-ios#154]
After installing the "InstantSearch" via CocoaPods, I am unable to run my project, and it's showing three build errors upon installing the pod. 

<img width="1648" alt="Screen Shot 2020-12-23 at 6 22 13 PM" src="https://user-images.githubusercontent.com/19779880/103043754-02b24280-454c-11eb-9618-3e5f883ff251.png">

**Comment by VladislavFitz** [comment]
Hi @ferrlan ,
Could you precise the versions of InstantSearch and Swift client libraries you use?
You can find them in the `Podfile.lock` file as `AlgoliaSearchClient` and `InstantSearch` pods.

**Comment by ferrlan** [comment]
![Screen Shot 2020-12-24 at 10 15 08 PM](https://user-images.githubusercontent.com/19779880/103116760-84ca6600-4635-11eb-9719-dbc66684cb56.png)

Absolutely. Here is that. Also, I found that I can import InstantSearch in my app delegate with no error, but its not until I add the "Insights.register" line that the app shows the error when building. Thank you

**Comment by VladislavFitz** [comment]
The versions of the libraries are correct, but the code I see on the screenshot above is outdated. 
Try to remove InstantSearch dependency, clear Cocoapods caches, and then add InstantSearch dependency again.
Regarding the issue with Insights, there is actually an error in the Podspec. The patch will be released soon, I'll keep you informed.

**Comment by ferrlan** [comment]
Thank you! @VladislavFitz

**Comment by VladislavFitz** [comment]
The issue has been fixed with the [patch 7.6.2](https://github.com/algolia/instantsearch-ios/releases/tag/7.6.2)
