### ISSUE TITLE
Xcode 12.5 (Fastlane) Archive Fails

### ISSUE THREAD

**Issue by Sam-Spencer** [algolia/instantsearch-ios#172]
**Describe the bug 🐛**
Building fails with "unknown type" errors (see screenshot) that suggest the compiler doesn't realize you're referencing SwiftUI for some reason. While this seems like it might be a compiler bug, an easy fix is to add `import SwiftUI` statements to any files requiring it.

**To Reproduce 🔍**
1. Attempt to archive a build via Fastlane including this project vis SPM.
2. Building and archiving fails.

**Expected behavior 💭**
Builds should succeed.

**Screenshots 🖥**
<img width="100%" alt="Screen Shot 2021-05-08 at 6 44 22 PM" src="https://user-images.githubusercontent.com/2374407/117556353-810c0e80-b02d-11eb-9d08-5b527282aae2.png">

**Environment:**
 - OS: iOS
 - Version 7.11.0

**Comment by jwells89** [comment]
I'm seeing this behavior as well with manual archiving. Debug builds targeting the simulator and physical devices build fine. Have tried versions of InstantSearch from 7.6.2 up to 7.11.0 to no avail.

**Environment**
- Xcode 12.5
- SwiftPM
- iOS 13.0 target

**Comment by mschinis** [comment]
I just ran into the same issue as above. Building for distribution via fastlane.

**Environment**
- Xcode 12.5
- Swift Package Manager
- iOS 14.1 target

_**Screenshot for reference**_  
<img width="715" alt="Screenshot 2021-05-18 at 16 05 15" src="https://user-images.githubusercontent.com/771903/118656227-01cbc700-b7f3-11eb-9236-4d49135aa9cb.png">

**Comment by Sam-Spencer** [comment]
Found a temporary workaround when using fastlane or any automated `xcodebuild` system:

 1. Clean your build prior to beginning a new one
 2. Prior to building run the following in your project directory:
    
    ```bash
    Dir.chdir("../") do
      sh("xcodebuild","-resolvePackageDependencies")
    end
    ```
 3. Build and archive.
 
 IMO, this type of workaround shouldn’t be necessary. But it might indicate an issue with SPM and Xcode rather than algolia!

**Comment by VladislavFitz** [comment]
Thank you for reporting this. The fix is in progress. In the meantime feel free to downgrade to 7.10 as 7.11 only introduces the SwiftUI components.

**Comment by alelordelo** [comment]
Also ran into this issue when archiving.

Downgrading to 7.10 have me 20 erros (instead of 5 on 7.11). My implementation is exactly the same as Algolia SwiftUI tutorial

**Comment by VladislavFitz** [comment]
@alelordelo  The 7.11.1 patch is available via SPM (will be available later via Cocoapods as well). Please try it and confirm if it fixes the issues.

**Comment by alelordelo** [comment]
thanks, will test now via SPM

**Comment by alelordelo** [comment]
yup, worked! thanks for the quick reply mate!
