### ISSUE TITLE
Xcode 13 beta - error: Segmentation fault: 11 (in target 'InstantSearchInsights' from project 'InstantSearch')

### ISSUE THREAD

**Issue by alelordelo** [algolia/instantsearch-ios#175]
**Describe the bug 🐛**
When build on Xcode Beta 13, Xcode won't build and gives this error:
 error: Segmentation fault: 11 (in target 'InstantSearchInsights' from project 'InstantSearch')

**Screenshots 🖥**
<img width="1437" alt="Screenshot 2021-06-08 at 12 26 23" src="https://user-images.githubusercontent.com/17708751/121172977-8d67cf00-c858-11eb-921f-59129708a6e0.png">

**Environment:**
macOS Big Sur 11.4 (20F71)

**Comment by VladislavFitz** [comment]
Hi @alelordelo,

Thanks for reporting this. 
I will investigate this soon.

**Comment by alelordelo** [comment]
thanks @VladislavFitz , any update on this? Just waiting for this to be fixed so I can test my app on Xcode Beta

**Comment by VladislavFitz** [comment]
Hi @alelordelo, 
Sorry for the delay. I created a [PR](https://github.com/algolia/instantsearch-ios/pull/179) which might fix the Xcode 13 related issues.
As explained in the PR's comment, after fixing the segfault, the compiler still produces a lot of obscure errors, so I wait for the next Xcode beta(s) before proceed as it seems to be an internal compiler issue.

**Comment by alelordelo** [comment]
great, thanks for looking into this VladislavFitz!

**Comment by VladislavFitz** [comment]
Hi @alelordelo and @keremcesme !
I managed to detect the source of the segmentation faults and other compiler issues. 
As I supposed, they are related to Swift 5.5 compiler issues and I found a workarounds. 
I keep the fixes in the `fix/xcode13-issues` branch until the Xcode 13 release, hoping the compiler issues will be fixed.  
In the meantime you can use this branch in your tests. 
Thanks for your patience!

**Comment by keremcesme** [comment]
Hi @VladislavFitz ,
May I know the Xcode beta 13 version you are testing? 
I hope all problems will be solved when IOS 15 version is released 🙏
I appreciate your efforts.

**Comment by VladislavFitz** [comment]
Hi @keremcesme ,
I tested with Xcode 13 beta 4.

**Comment by timdegraw** [comment]
Any updates on this? Looks like `fix/xcode13-issues` branch hasn't been merged yet. When should we expect a release?

**Comment by VladislavFitz** [comment]
The branch has been merged and the changes are available in the version [7.13.3](https://github.com/algolia/instantsearch-ios/releases/tag/7.13.3)
