### ISSUE TITLE
SwiftUI demo not working whrn targeting MacOS

### ISSUE THREAD

**Issue by alelordelo** [algolia/instantsearch-ios#176]
**Describe the bug 🐛**
I am following this tutorial:
https://www.algolia.com/doc/guides/building-search-ui/getting-started/how-to/declarative/ios/

When targeted iOS, the demo works fine:

When targeted MacOS, the demo doesnt work and Xcode does not recognize SearchBar( )

Really appreciate any inputs on how I can fix this!

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**
Xcode Version 12.5 (12E262)
MacOS Big Sur 11.4 (20F71)

**Comment by alelordelo** [comment]
fixed, issues was with 

     // .background(Color(.systemGray5))

**Comment by VladislavFitz** [comment]
Completely fixed in #217
