### ISSUE TITLE
Xcode 13 Beta 1 Segmentation fault: 11

### ISSUE THREAD

**Issue by keremcesme** [algolia/instantsearch-ios#177]
While not getting any errors in Xcode 12 versions, I started getting Segmentation fault: 11 error with Xcode 13 Beta 1. The error message is: 
`error: Segmentation fault: 11 (in target 'InstantSearchInsights' from project 'InstantSearch')`

<img width="1386" alt="Screen Shot 2021-07-04 at 16 20 08" src="https://user-images.githubusercontent.com/69275985/124386565-b5c1dc80-dce3-11eb-8f33-b10f56821a73.png">
<img width="253" alt="Screen Shot 2021-07-04 at 16 20 24" src="https://user-images.githubusercontent.com/69275985/124386573-be1a1780-dce3-11eb-97f1-03b8875023d5.png">

**Comment by VladislavFitz** [comment]
Hi @keremcesme. 
The issue related to this problem is already [created](https://github.com/algolia/instantsearch-ios/issues/175), so I close this one.
