### ISSUE TITLE
Compile error, Variable used within its own initial value

### ISSUE THREAD

**Issue by StrelnikovEugene** [algolia/instantsearch-ios#188]
**Describe the bug 🐛**
File DynamicFacetListInteractor+FilterState.swift

https://github.com/algolia/instantsearch-ios/blob/52508ca563734582ee29986dd84bdb8f82bb34f0/Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor%2BFilterState.swift#L65

Compile error: Variable used within its own initial value (groupID)

**Comment by VladislavFitz** [comment]
Hi @StrelnikovEugene ,
​Thank you for reporting this issue. 
​It was fixed in the patch 7.13.2.
