### ISSUE TITLE
Xcode 13 RC Instansearch Errors

### ISSUE THREAD

**Issue by keremcesme** [algolia/instantsearch-ios#194]
I am getting 51 new instasearch error in xcode 13 RC version. I don't get any error while building for simulator or device. But when archiving and building for Any IOS Devices (arm64) I get an error.
<img width="1472" alt="Screen Shot 2021-09-19 at 15 13 05" src="https://user-images.githubusercontent.com/69275985/133927053-71fe1bb7-2130-4ae2-9a98-974dfea27d9e.png">

**Comment by keremcesme** [comment]
EDIT: The bug persists in Xcode 13 Release Version (13.0).

**Comment by VladislavFitz** [comment]
Hi @keremcesme,
Thank you for reporting this issue, I'm actively working on a solution

**Comment by VladislavFitz** [comment]
@keremcesme  Could you confirm if it works proprely with the fix?

**Comment by keremcesme** [comment]
@VladislavFitz I verified that the` fix/xcode13-archive-issue` branch resolved the bug. Thanks for your efforts 🙏
