### ISSUE TITLE
InstantSearch not working with Swift 5.5

### ISSUE THREAD

**Issue by devJAdam** [algolia/instantsearch-ios#199]
**Describe the bug 🐛**
I am not able to import InstantSearch with Swift 5.5. I get the following errors. 
-Could not find module 'InstantSearch' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
-Module compiled with Swift 5.4 cannot be imported by the Swift 5.5 compiler:
**To Reproduce 🔍**
1. Add InstantSearch to your Project
2. import InstantSearch

**Expected behavior 💭**
You should be able to import and use InstantSearch

**Screenshots 🖥**
-

**Environment:**
 - InstantSearch iOS 7.13.5
 - Xcode 13 on ARM Mac running macOS Big Sur
 - I used CocoaPods and also tried with Swift Package Manager

**Comment by VladislavFitz** [comment]
Hi @devJAdam ,

Thank you for reporting this. Could you precise which dependency manager do you use to add InstantSearch to your project?

**Comment by devJAdam** [comment]
Hello
I used with CocoaPods and also tried with Swift Package Manager

**Comment by VladislavFitz** [comment]
Looks like you are trying to embed a precompiled library to your project. 
Normally, when you add InstantSearch dependency via SPM/Cocoapods you fetch the source code which is compiled then on your machine. Could you try to remove the InstantSearch dependency, fully clean your project and Dervied Data folder and try to add it again?

**Comment by devJAdam** [comment]
Hi
I just did removed and added InstantSearch again using SPM and it worked! Thanks for helping!

**Comment by VladislavFitz** [comment]
Great!
