### ISSUE TITLE
Result updated, but attribute not selected

### ISSUE THREAD

**Issue by denikaev** [algolia/instantsearch-ios#21]
Hi. i faced with bug. If i pressed on three attribute i see result "0", but third attribute not selected.
You can check screen record on the link. [https://drive.google.com/file/d/1Iz3x67V_mjBE8TRipQcXt3_mkYbJnML_/view?usp=sharing](url)

My code:

   ```swift
class SearchTableViewController: UITableViewController {

  @IBOutlet weak var resultButton: StatsButtonWidget!
  
  override func viewDidLoad() {
      super.viewDidLoad()
      
      addResultButtonView()
      
      InstantSearch.shared.registerAllWidgets(in: self.view)
      
      LayoutHelpers.setupResultButton(button: resultButton)
      resultButton.addTarget(self, action: #selector(resultButtonClicked), for: .touchUpInside)
      
  }
  
  private func addResultButtonView() {
      
      view.addSubview(resultButton)
      
      resultButton.resultTemplate = "Показать {nbHits} результат(-а/-ов)"
      
      resultButton.layer.zPosition = 5
      
      resultButton.translatesAutoresizingMaskIntoConstraints = false
      resultButton.leftAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.leftAnchor).isActive = true
      resultButton.rightAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.rightAnchor).isActive = true
      resultButton.bottomAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.bottomAnchor).isActive = true
      resultButton.widthAnchor.constraint(equalTo: tableView.safeAreaLayoutGuide.widthAnchor).isActive = true
      resultButton.heightAnchor.constraint(equalToConstant: 40).isActive = true // высота кнопки 
      
  }
  
  @objc func resultButtonClicked() {
      
      if let viewController = storyboard?.instantiateViewController(withIdentifier: "resultVC") as? ResultViewController {
          
          let backItem = UIBarButtonItem()
          backItem.title = "Поиск"
          self.navigationItem.backBarButtonItem = backItem
          
          self.navigationController?.pushViewController(viewController, animated: true)
          
      }
      
  }
  
}
```

![2017-12-05 13 20 42](https://user-images.githubusercontent.com/29748197/33602036-263b40c2-d9bf-11e7-96cc-8f2451607f94.png)

**Comment by spinach** [comment]
Hey @denikaev,

Can you please post the code for the `tableView(cellForRowAt:containing:with:is)` of the `Refinement Table Widget`? Would like to see if there is something wrong done there.

**Comment by denikaev** [comment]
Hi. Code is here:

import UIKit
import InstantSearch

class InteriorSearchTableViewController: UIViewController, RefinementTableViewDataSource {

    @IBOutlet weak var tableView: RefinementTableWidget!
    
    var refinementController: RefinementController!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        refinementController = RefinementController(table: tableView)
        tableView.dataSource = refinementController
        tableView.delegate = refinementController
        refinementController.tableDataSource = self
        
        InstantSearch.shared.registerAllWidgets(in: self.view)
        
        InstantSearch.shared.register(widget: tableView)
        
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath, containing facet: String, with count: Int, is refined: Bool) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "refinementCell", for: indexPath) as! FacetTableViewCell
        
        cell.facet = facet
        cell.count = count
        cell.isRefined = refined
        
        return cell
        
    }
    
}

**Comment by denikaev** [comment]
It's working with containerView. Like as in screenshot
![2017-12-06 10 37 04](https://user-images.githubusercontent.com/29748197/33650083-8acce6dc-da71-11e7-9417-ec2ecf4ee717.png)
Each attribute have personal viewController.

**Comment by spinach** [comment]
@denikaev I don't see anything weird with the code sample you posted. It looks fine to me... From the screen recording, i see that selecting and unselecting the last row does have an effect: it changes the number of results. The problem is in the UI where the checkmark is not being shown. I would put a breakpoint on the `cellForRowAt` method and see what's going on with the refined value. 

It seems you made it work though with the container views which is great. If you need more help, you can re-open this issue.
