### ISSUE TITLE
Not able to set log level

### ISSUE THREAD

**Issue by materik** [algolia/instantsearch-ios#245]
**Describe the bug 🐛**
Not able, or not clear enough documentation for how, to set log level.
The project prints this in the log but there is no public properties that I can find to do this:
```Algolia Search Client Swift: Default minimal log severity level is info. Change Logger.minLogServerityLevel value if you want to change it.```

**Expected behavior 💭**
A public property to set log level. Clear instructions of how to do this.

**Environment:**
 - OS: mac
 - Version: 12.4

**Additional context**
Version 7.19

**Comment by VladislavFitz** [comment]
Hi @materik ,
Thank you for reporting this issue. I'll check it and come back to you soon.

**Comment by materik** [comment]
👏
