### ISSUE TITLE
Add custom JSONDecoder property to HitsInteractor

### ISSUE THREAD

**Issue by VladislavFitz** [algolia/instantsearch-ios#247]
**Is your feature request related to a problem? Please describe 🙏**

Described [here](https://discourse.algolia.com/t/instantsearch-ios-set-decoding-strategy-to-hitsinteractor/15939).
Client wants the `Codable` model variable names to be in camel case.
`HitsInteractor` supports only the snake case since it uses the default `JSONDecoder` constructor, so the client might add `CodingKeys` per model. 

**Describe the solution you'd like 🤔**
Add possibility to set a custom `JSONDecoder` property to `HitsInteractor` responsible for search hits decoding.

**Comment by steffidg** [comment]
@VladislavFitz  
I found a minor issue on one of the constructor where the jsonDecoder parameter value is not passed.
```
  convenience public init(infiniteScrolling: InfiniteScrolling = Constants.Defaults.infiniteScrolling,
                          showItemsOnEmptyQuery: Bool = Constants.Defaults.showItemsOnEmptyQuery,
                          jsonDecoder: JSONDecoder = JSONDecoder()) {
    let settings = Settings(infiniteScrolling: infiniteScrolling,
                            showItemsOnEmptyQuery: showItemsOnEmptyQuery)
    self.init(settings: settings)
    // Expected
    // self.init(settings: settings,  jsonDecoder: jsonDecoder)
  }
```

**Comment by VladislavFitz** [comment]
Great catch @steffidg , the [fix](https://github.com/algolia/instantsearch-ios/pull/257) is on its way 👌
