### ISSUE TITLE
Pagination for HitsController not working sometimes in iOS

### ISSUE THREAD

**Issue by winstoncex7** [algolia/instantsearch-ios#250]
**Describe the bug 🐛**
Pagination in Hits Controller doesn't work sometimes.

**To Reproduce 🔍**
1. Scroll Products on hits controller 7-8 times
2. Then apply Sort By A-Z
3. List autoscrolls to top
4. Now scroll the list it doesn't load new products. (Pagination is not working)

**Expected behavior 💭**
On reaching the last product the list should load new products.

**Environment:**
 - OS : iOS
 - Version : iOS 15.2

**Comment by VladislavFitz** [comment]
Hi @winstoncex7,
Thank you for reporting this issue. We will investigate it soon.

**Comment by VladislavFitz** [comment]
Hi @winstoncex7, 
I didn't manage to reproduce the issue in the [*SortBy*](https://github.com/algolia/instantsearch-ios/tree/master/Examples/Showcase/Sort/SortBy) target of the provided [Examples project](https://github.com/algolia/instantsearch-ios/tree/master/Examples). The pagination works as expected for all indices. 
Could you share the code snippet with your setup of InstantSearch components?

**Comment by VladislavFitz** [comment]
Hi @winstoncex7 ,
Due to a lack of response from your side, I close this issue. 
Feel free to reopen it providing more details.
