### ISSUE TITLE
Incorrect facet selected attribute value on Hierarchical filter

### ISSUE THREAD

**Issue by steffidg** [algolia/instantsearch-ios#251]
**Describe the bug 🐛**
On Hierarchical Filters , facet is still selected upon clearing. It also crashes when that remaining selected item is reselected.

**To Reproduce 🔍**
1. Go to Hierarchical Filters on example project.
2. Click on Book -> Book > Romance
3. Clear filters

**Expected behavior 💭**
There's no selected facet. 

To trigger crash:
5. Select "Book"

Crash details:
```
 Fatal error: 'try!' expression unexpectedly raised an error: InstantSearchCore.QueryBuilder.Error.queriesResultsCountMismatch(3, 1)
```

**Screenshots 🖥**
![Screen Shot 2022-09-05 at 10 29 23 PM](https://user-images.githubusercontent.com/81630747/188476842-12f2c2e0-94e7-45a7-ab0f-bd5834a7d729.png)
You'll see that there's no filters applied but Book is selected. I checked the item attributes and it prints `isSelected = true`

**Environment:**
 - OS: iOS 15.5

**Additional context**

Not sure but this could be related so I'm adding this here as well. On my own project integration (using v7.19.0), when I click on an item that's already selected this happens:
1. Item gets deselected `is_selected = false`
2. But on reload, item's parent `is_selected = true` .

Expected:
Item's parent should also be deselected.

Attaching a video for clarity.
https://user-images.githubusercontent.com/81630747/188477799-1fc75fc6-029f-409a-947c-6f20a2c8bac4.mp4
You'll see that every time I click "Baby care", the table reloads and preselects "Mom and Baby"

Here are code snippets
```
// Tableview
        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        //... dequeuing cell here
        
            let maxSelectedLevel = Set(items.filter { $0.isSelected }.map { $0.level }).max() ?? 0
            let item = items[indexPath.row]
            cell.indentationLevel = item.level
            cell.selectionStyle = .none
            cell.isChecked = (item.level == maxSelectedLevel) && item.isSelected
            return cell
        }
        
        func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
            let item = items[indexPath.row]
            onClick?(item.facet.value)
        }

// Connector
        categoriesConnector = .init(searcher: searcher,
                                    filterState: filterState,
                                    hierarchicalAttributes: hierarchicalAttributes,
                                    separator: " > ",
                                    controller: controller,
                                    presenter: DefaultPresenter.Hierarchical.present)
```

I'm also wondering as to why unlike on the example project, mine deselects the item when `onClick...` is called on an item that's already selected.

**Comment by VladislavFitz** [comment]
Hi @steffidg ,
Thank you for reporting this issue. We will investigate it soon.
