### ISSUE TITLE
When simulating a device, performance is snappy

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-ios#30]
From [support](https://secure.helpscout.net/conversation/556070111/57448?folderId=1106255):
> Has anyone reported performance issues when running a build off Xcode on hardware? When simulating a device, performance is snappy. When I search while running the build on my iPhone X, it's crawling. I haven't found an explanation for this, so figured I'd ask.

**Comment by spinach** [comment]
Thanks PLN, I replied to the customer, closing for now until confirmation of the issue.
