### ISSUE TITLE
Breaking changes in dependencies

### ISSUE THREAD

**Issue by squarefrog** [algolia/instantsearch-ios#305]
**Describe the bug 🐛**
Originally reported in [`algoliasearch-client-swift`](https://github.com/algolia/algoliasearch-client-swift/issues/854) but it feels more relevant here. Feel free to close that issue if you like.

One of `instantsearch-ios` dependencies has introduced a breaking change that prevents `instantsearch-ios` from building on iOS 15. It bumps the minimum target to iOS 14, but `instantsearch-ios` has a minimum target of iOS 9. This prevents compilation, even if you are targeting a higher version than iOS 9.

**To Reproduce 🔍**
1. Clone this project
2. Open the Example Xcode project
3. Wait for package resolution
4. Attempt to build

**Expected behavior 💭**
Example project should build.

**Screenshots 🖥**
<img width="1552" alt="Screenshot 2024-02-02 at 15 42 58" src="https://github.com/algolia/instantsearch-ios/assets/343450/ba229968-2d0b-4470-ba68-38241a554790">

**Environment:**
 - OS: iOS
 - Version 15+
 - Xcode 15

**Additional context**
You can work around this issue by manually adding `https://github.com/algolia/algoliasearch-client-swift` to your project, and setting the resolution rule to be `exact: 8.19.0`

<img width="1088" alt="Screenshot 2024-02-02 at 15 44 54" src="https://github.com/algolia/instantsearch-ios/assets/343450/2ea62b40-c5bf-4ecf-8cac-e04d7c567c92">

**Comment by VladislavFitz** [comment]
Hi @squarefrog ,
That's indeed an unexpected breaking change.  Thanks for flagging this! 
We're preparing an update for InstantSearch iOS to fix it. Expect a release soon. 
Meanwhile, your workaround with the explicit client version setting is a good interim solution.

**Comment by squarefrog** [comment]
Sounds good!

**Comment by r3econ** [comment]
Hi @VladislavFitz when would the fix go live? Our CI workflows fail with the above-mentioned error

**Comment by RebinX1** [comment]
hi is there a fix for this yet?

**Comment by salami** [comment]
Also waiting on a fix for this

**Comment by r3econ** [comment]
Any update? We'd love to have it fixed :)

**Comment by akshaaatt** [comment]
Any update on this?

**Comment by r3econ** [comment]
@nickvlku any chance having this fixed? 🥲

**Comment by NicolasBrunnerSRF** [comment]
> We're preparing an update for InstantSearch iOS to fix it. Expect a release soon.

For when can we expect this release? We might have different definitions of "soon" 😒

**Comment by dhayab** [comment]
@NicolasBrunnerSRF have you tried updating instantsearch-ios to [v7.26.2](https://github.com/algolia/instantsearch-ios/releases/tag/7.26.2)? It was released a few ago and realigned supported platform versions with the API client library.

**Comment by squarefrog** [comment]
As far as I’m concerned 7.26.2 does indeed fix this and the issue should be closed.

**Comment by NicolasBrunnerSRF** [comment]
@dhayab I can also confirm that v7.26.2 does fix the issue 🥳 Thanks for the update!
