### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by tatejennings** [algolia/instantsearch-ios#309]
**Is your feature request related to a problem? Please describe 🙏**
Add privacy manifest file to that describes reason for using the API `UserDefaults`

[Privacy Manifest Files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)
[Required Reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

**Describe the solution you'd like 🤔**
Add privacy info file describing the use of `UserDefaults` with the [reason](CA92.1) `CA92.1`

**Comment by tatejennings** [comment]
Is there any updates to this issue ?

**Comment by timdegraw** [comment]
@VladislavFitz is this SDK being maintained still?

**Comment by timdegraw** [comment]
> Privacy manifests can be found below. We'll be publishing an issue/guide shortly. InstantSearch iOS: https://github.com/algolia/instantsearch-ios/blob/master/Sources/PrivacyInfo.xcprivacy Swift API Client: https://github.com/algolia/algoliasearch-client-swift/blob/master/PrivacyInfo.xcprivacy

Will you be publishing a new release?

**Comment by loveraimogen** [comment]
Updates are being tracked here: https://github.com/algolia/instantsearch-ios/issues/313
