### ISSUE TITLE
Xcode 16 beta build error

### ISSUE THREAD

**Issue by arpa-srf** [algolia/instantsearch-ios#318]
**Describe the bug 🐛**
Build with instantsearch-ios as a dependency fails on Xcode 16 beta

Errors:

```
Type 'PageMap<Item>' does not conform to protocol 'Sequence'
Type 'PageMap<Item>' does not conform to protocol 'BidirectionalCollection'
Type 'PageMap<Item>' does not conform to protocol 'Collection'
```
**To Reproduce 🔍**
1. Create new Project
2. Add instantsearch-ios as a package dependency
3. Build project

(Also possible to reproduce with Examples project in repo)

**Expected behavior 💭**
Build succeeds

**Screenshots 🖥**
Errors in PageMap.swift
<img width="1104" alt="PageMap Errors" src="https://github.com/algolia/instantsearch-ios/assets/58429208/335d1d33-d1ac-4d83-ab1f-ecf44f696855">

**Environment:**
 - macOS Version 15.0 beta (24A5264n)
 - Xcode Version 16.0 beta (16A5171c)
 - instantsearch-ios Version 7.26.2

**Comment by r3econ** [comment]
I'm facing the same problem, is there any fix planned?

**Comment by mohpor** [comment]
Same

**Comment by NolanOfficial** [comment]
Same issue here

**Comment by squarefrog** [comment]
We just removed the conformance to Sequence ([remove these lines](https://github.com/algolia/instantsearch-ios/blob/1430cf9b998c04682116b5e134f4181a1f800bf6/Sources/InstantSearchCore/Pagination/PageMap.swift#L84-L88)) and it builds without issue. Given this is an internal type and no errors are thrown its likely this isnt used anymore.

This allowed us to build our project with Xcode 16

1. Clone `instantsearch-ios`
2. Remove the conformance to Sequence from `PageMap.swift`
3. In Xcode go to add a local package, and pick your cloned instantsearch dir
4. Say yes you want to replace existing package
5. Add the targets you need
6. Build

It should go without saying that this is recommended only for trying Xcode 16 and not for shipping.

**Comment by r3econ** [comment]
@LukyVj @mobilealgolia @robertmogos @aallam @francoischalifour Do you know when the new version of the library with the fix will be available? Currently, a problem with the library is blocking testing of an application using the latest iOS
