### ISSUE TITLE
SearchBarWidget, add support for searchBarSearchButtonClicked

### ISSUE THREAD

**Issue by manishtpatel** [algolia/instantsearch-ios#32]
override public func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        resignFirstResponder()
    }

Current implementation assigns self as delegate, so we can't make our viewcontroller delegate for searchbarwidget. Way searchbarwidget works it is ideal to close the keyboard upon clicking search. Either supporting above method will help or need way of controlling searchbutton clicked

**Comment by spinach** [comment]
Hey @manishtpatel ,

Yes you are right, we are working on making the API more flexible and customisable. In the meantime, I think this [SearchViewModel](https://community.algolia.com/instantsearch-ios/concepts.html#searchviewmodel) can help you instead of using the SearchBarWidget.
