### ISSUE TITLE
Duplicate Sort Options Displayed in Search Filters

### ISSUE THREAD

**Issue by Ma7m0udalaa** [algolia/instantsearch-ios#327]
In the example project using Grep, the "Sort By" and "Relevant Sort" dropdown menus are displaying duplicate options. This is incorrect behavior and causes a confusing experience for users.

Each sort option (such as Most Relevant, Default) should only be displayed once in the dropdown.

**Actual Behavior**
The "Sort By" and "Relevant Sort" dropdowns contain multiple instances of the same sort option. See the attached screenshots for reference.

**Screenshots**
![RelevantSearch](https://github.com/user-attachments/assets/9e9e79b5-8698-42d0-affc-d57f4d34faac)
![SortBy](https://github.com/user-attachments/assets/6730ace4-b207-45c4-883d-23de1a19c2ae)

**Impact**
Causes confusion by showing redundant sorting choices.
Reduces usability and affects navigation within the example.

**Steps to Reproduce**
Launch the example project using the git repo itself.
Go to **Declarative UI**  section where sorting options can be selected.
Open the "Sort By" or "Relevant Sort".
Notice the repeated options in the dropdown menus.

**Comment by Ma7m0udalaa** [comment]
@dhayab  which version should I use to get the latest fix? My current version is 7.26.3

**Comment by dhayab** [comment]
Hi, the fix will be part of the next instantsearch-ios release, the week of December 9th.
