### ISSUE TITLE
'No results available' message displayed while fetching the initial data

### ISSUE THREAD

**Issue by manishtpatel** [algolia/instantsearch-ios#38]
I have implemented HitsTableViewController, it takes around few seconds to fetch the initial search result. Table displays 'No results available' message while data is not loaded.

Message should only be displayed once data is fetched and no records are available. It should render the empty table while fetching the data.

**Comment by spinach** [comment]
Hi @manishtpatel ,

Thanks for the good feedback. This is indeed something we can improve. 

In the meantime, there is a way for you to customise this "no result" view with the [following datasource methods](https://community.algolia.com/instantsearch-ios/widgets.html#empty-view). You can use it in conjunction with the notifications sent you by the searcher (Check this [page](https://community.algolia.com/instantsearch-core-swift/guide/search.html) at the bottom in the `Events` section). 

I will keep this issue open until we offer a better feedback on initial fetching of the data.

**Comment by manishtpatel** [comment]
@spinach for considering this, meanwhile for someone trying to solve this problem. Below is the hack

Override viewForNoResults and based on notifications from Searcher maintain a flag and return the view as needed.
func viewForNoResults(in tableView: UITableView) -> UIView

**Comment by zeeshansuleman** [comment]
@spinach I am facing that issue. How can I solve that issue? On you reply you gives two source links but those are not working right now.
