### ISSUE TITLE
Application rejected due to NSSpeechRecognitionUsageDescription 

### ISSUE THREAD

**Issue by azharashiq178** [algolia/instantsearch-ios#45]
Kindly someone guide me regarding this one, i've added NSSpeechRecognitionUsageDescription key in info.plist but still getting rejected. Apple response is as following.
 
--
 
Dear Developer,We identified one or more issues with a recent delivery for your app, "App Name". Please correct the following issues, then upload again.Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSSpeechRecognitionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).Best regards,The App Store Team

**Comment by azharashiq178** [comment]
I am not using voice-overlay, i am using 'InstantSearch-iOS' and 'AlgoliaSearch-Client-Swift'. And while uploading app binary is reject with the above description.

**Comment by robertmogos** [comment]
Are you using at any point the Speech framework from Apple ? We don't use it `InstantSearch-iOS` nor in `AlgoliaSearch-Client-Swift`

**Comment by azharashiq178** [comment]
no i am not using but there is a file name SpeechController.swift in InstantSearch-iOS pod due to this apple has rejected i think which is not used in my app.

**Comment by robertmogos** [comment]
Gotcha. Indeed, this was removed in `InstantSearch-iOS 3.0.0`. Could you update it ?

**Comment by azharashiq178** [comment]
i had version 2.1.1. I will update it then will submit app.
Thanks
