### ISSUE TITLE
Changing index of InstantSearch in real-time || InstantSearch remove/add widgets

### ISSUE THREAD

**Issue by MohamedRed** [algolia/instantsearch-ios#51]
Hello, 

Is there any possibility to change the index used by InstantSearch in real-time depending on user's index selection ? 
I have seen that there have been improvements done in instantsearch.js : 
https://github.com/algolia/instantsearch.js/pull/2384
https://github.com/algolia/instantsearch.js/issues/2424
Do we have the same in swift ? 
Thanks for your help !

**Comment by spinach** [comment]
Hi @MohamedRed ,

We're planning to add this kind of widget in IS.ios in the near future. In the meantime, you can do something like the following to change index:

```
        let appID: String = "someAppID"
        let apiKey: String = "someApiKey"
        let sortIndexName = "newIndexName"
        let client = Client(appID: appID, apiKey: apiKey)
        let sortIndex = client.index(withName: sortIndexName)

        // Make the index swap
        InstantSearch.shared.getSearch().index = sortIndex
        // execute a search on the new index so that all the views reload with data from new index
        InstantSearch.shared.getSearch().search()
```

Not the best developer friendly sample, but we'll wrap this up nicely in a widget soon. Thank you for your feedback!
