### ISSUE TITLE
How to know if HitsCollectionWidget is refined ?

### ISSUE THREAD

**Issue by Geoffrey63** [algolia/instantsearch-ios#69]
Hi, 

I use a HitsCollectionWidget combined with a RefinementController.
On the view containing the HitsCollectionWidget, I would like to display an indicator if the collection is refined.
Is there a way to know if a collectionWidget is refined ?

Thank you for your reply

**Comment by spinach** [comment]
Hi @Geoffrey63 ,

you can access the refinements of an index through the `SearchParameter` class. Basically, doing `InstantSearch.shared.params` gives you access to the search parameters if you're only using one index. Then you can call the `hasNumericRefinements()`or `hasFacetRefinements()` or `hasRefinements()` on it. 

Let us know if you have more issues concerning this!
