### ISSUE TITLE
Add "fake" UITableView row when no hits

### ISSUE THREAD

**Issue by flashadvanced** [algolia/instantsearch-ios#70]
Hello, Algolia community!

When using the `MultiHitsTableWidget` the table view gets populated when there are results and that's totally fine. As my table view cells serve as action triggers when tapped, I miss the case when there are no results. Is there any way I can add a "fake" result row in the table view which has the exact same text as what the user has typed in the search bar? Any leads will be highly appreciated.

**Comment by spinach** [comment]
Hey @flashadvanced ,

If you want to customise your multi hits table widget, you will probably need to use our ViewModel for it. Check out our [docs here](https://www.algolia.com/doc/api-reference/widgets/multi-hits/ios/?language=swift#multihitsviewmodel) concerning this and let us know if you face any issues!
