### ISSUE TITLE
Custom AlgoliaWidget with multi index

### ISSUE THREAD

**Issue by Geoffrey63** [algolia/instantsearch-ios#71]
Hi, 

I use a collectionView (HitCollectionWidget) to display a collection of products.
I need to sort those items by price. 

As seen in #34, i switched to a multi-index configuration in order to be able to switch from the regular index to the price-sorted index.

For some the `HitsCollectionWidget` and the `SearchBarWidget`, I had to specify the used index, using `getSearched` to retrieve the index : 
```swift
searchBar.index = (InstantSearch.shared.getSearcher(named: algoliaBackOfficeOfferChannel)?.indexName)!
```

Everything works fine but I have an issue on a custom Widget meant to dispaly the number of results that keeps displaying `0 résultat` (it works fine with a single index).
I changed from `AlgoliaWidget` to `AlgoliaIndexWidget` and set the index as this : 
```swift
nbResultsLabel.index = (InstantSearch.shared.getSearcher(named: algoliaBackOfficeOfferChannel)?.indexName)!
```

Here is the code of this widget : 
```swift
import UIKit
import InstantSearch
import InstantSearchCore

class NbResultsWidget: UILabel, AlgoliaIndexWidget, ResultingDelegate {
    
    @IBInspectable public var index: String = ""
    @IBInspectable public var variant: String = ""
    
    func on(results: SearchResults?, error: Error?, userInfo: [String: Any]) {
        
        guard let results = results else {
            return
        }
        
        if results.nbHits > 1 {
            self.text = "\(results.nbHits) résultats"
        } else {
            self.text = "\(results.nbHits) résultat"
        }
    }
}
```

Did I miss something in the widget configuration ?
Thank you for your help.

**Comment by spinach** [comment]
Hi @Geoffrey63 ,

Thanks a lot for the detailed explanation of your issue. We're working on a new version of InstantSearch which will simplify its customisation and extensibility. 

In the meantime, there is another person which had a similar issue to yours, and you can see the answer here https://github.com/algolia/instantsearch-ios/issues/43#issuecomment-419896819. Also make sure you specify the `index` value before registering your widgets to InstantSearch. I hope that answers your question!
