### ISSUE TITLE
scrollViewWillBeginDragging delegate on hitsController.collectionDelegate

### ISSUE THREAD

**Issue by KosratDAhmad** [algolia/instantsearch-ios#72]
Hi,

I can't get `scrollViewWillBeginDragging` because I assigned `collectionView.delegate = hitsController` so How can I get `hitsController.collectionDelegate` and `scrollViewWillBeginDragging`

**Comment by spinach** [comment]
Hey @KosratDAhmad,

We're working on improving the easy of customisation of InstantSearch in its new version. In the meantime, you can solve your issue in 2 ways: 

1- Use `ViewModels` that do not tie you to the delegates/datasources. Specifically for your case, you should use the HitsViewModel and you can read about it [here in the docs](https://www.algolia.com/doc/api-reference/widgets/hits/ios/?language=swift#hitsviewmodel).

2- You can use the base class `HitsTableViewController` which gives you access to all datasource/delegate methods. You can read about it in our Getting Started Guide [here](https://www.algolia.com/doc/guides/building-search-ui/getting-started/how-to/storyboard/ios/?language=swift#display-your-data-hits).
