### ISSUE TITLE
Swift 5 compatibility

### ISSUE THREAD

**Issue by thirdmanrecords** [algolia/instantsearch-ios#76]
When attempting to compile on Xcode 10.2, I am getting the following error in InstantSearchClient > Cache.swift > updateTimer()

'default' has been renamed to RunLoopMode.defaultRunLoopMode

**Comment by spinach** [comment]
Hello - There is a PR WIP https://github.com/algolia/instantsearch-ios/pull/75 for that. It is still unstable but we're working on it. You can follow our progress there. 

In case you're in a rush, there is also another way you can go about it: You can specify a legacy Swift version for each pod in case you want to use the stable version of InstantSearch built with Swift 4.2. You can see how it is done [here](https://stackoverflow.com/a/46690240/905425).
