### ISSUE TITLE
{nbHits} varies according to the index

### ISSUE THREAD

**Issue by Geoffrey63** [algolia/instantsearch-ios#79]
Hi, 
We have products displayed in a `HitsCollectionWidget` with a `StatsLabelWidget` displaying the number of results. 
We use 3 index to sort product (default, price ASC, price DESC)
When we switch the index, the number of hits varies (for example: 577 results for default index, 535 for price ASC and 544 for price DESC).
It's a strange behaviour for our customers.
Is there a way to refresh this `nbHits` count or make it more precise ?

**Comment by spinach** [comment]
Hey @Geoffrey63 ,

You can actually modify the index name of the `StatsLabelWidget` with the `index` field (and `variance` in case you are using one). You might need to re-register the widget in order for the results to take effect. 

Also, please note that we are working on a new version of InstantSearch that is more customisable and flexible that better addresses those kind of issues.

**Comment by Geoffrey63** [comment]
Thank you @spinach for your answer, 
I have no problem switching between differents `index`.
The issue is about the `nbHits` (see top left corner of the gif below) that varies according to the selected index (number of products are equals in each `index`). 

![algolia (1)](https://user-images.githubusercontent.com/1381553/58955705-ed749800-879c-11e9-8359-9dea03b1adce.gif)

Our customers are disrupted by the fact that changing the sort order impact the number of products.
Is there a trick to overcome this display ?

**Comment by spinach** [comment]
Sorry we completely missed the reply. With the new version of InstantSearch, we have better support for customisation of what is being shown. You can check our new docs [here](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/ios/).
