### ISSUE TITLE
Documentation for having the search bar in the navigation bar

### ISSUE THREAD

**Issue by thomassnielsen** [algolia/instantsearch-ios#83]
The only reference I've found for how to put the search bar in the navigation bar is from [the Movies example project](https://github.com/algolia/instantsearch-ios-examples/blob/master/Movies/Movies/ViewController.swift#L32), which is outdated. This method no longer works, because the new SearchBarController is not a UISearchController. 

Is there any way to accomplish this with InstantSearch 5? If so, it would be nice to have it documented. The old sample project(s) should probably be updated or removed.

**Comment by VladislavFitz** [comment]
Hello Thomas. 

Thank you for your question and your feedback.
The behaviour you expect is easy to achieve with InstantSearch. 
Just follow this [example](https://www.algolia.com/doc/api-reference/widgets/search-box/ios/#examples).
But when you instantiate your `SearchBarController`, wrap the `UISearchController`'s searchBar into it as follows:

```swift
let searchController: UISearchController = ...
searchBarController = .init(searchBar: searchController.searchBar)
```

Then set searchController property of navigation item of your ViewController to put the search bar in the navigation bar:
```swift
navigationItem.searchController = searchController
```

We just added an item in our backlog to document the `UISearchController` and update our demos. Thanks again for giving us feedback on this.
