### ISSUE TITLE
Value of type 'TreeModel<Hit<Movie>.HighlightResult>' has no subscripts

### ISSUE THREAD

**Issue by nabs107** [algolia/instantsearch-ios#86]
**Describe the bug 🐛**
While building the demo project following error appears:
1. Value of type 'TreeModel<Hit<Movie>.HighlightResult>' has no subscripts

**To Reproduce 🔍**
1. Clone the project
2. Build the project

**Comment by spinach** [comment]
Hello @nabs107 - Just to make sure, are you referring to this [demo project](https://github.com/algolia/instantsearch-ios-examples/tree/master/DemoDirectory)?

**Comment by spinach** [comment]
I was able to reproduce this, will work on a fix.

**Comment by tompowered** [comment]
+1

**Comment by spinach** [comment]
You can now pull from `master` and it should work now. Thanks for reporting this
