### ISSUE TITLE
Filter.Numeric not working with large integer (i.e. timestamps)

### ISSUE THREAD

**Issue by aplusm** [algolia/instantsearch-ios#97]
**Describe the bug 🐛**
I have a date_timestamp in my index, and would like to add a Filter.Numeric to my FilterState. 
The filter is not respected and no results is returned.

**To Reproduce 🔍**
```
let nowTimestamp = Float(NSDate().timeIntervalSince1970)
let filter = Filter.Numeric(attribute: "date_timestamp", operator: .greaterThanOrEqual, value: nowTimestamp)
filterState[and: "calendar"].add(filter)
...
```

This doesn't returns any results as it should be, based on my index data.

**Expected behavior 💭**
The filter should returns the correct answer.

**Environment:**
 - OS: iOS
 - Version 5.2.2

**Comment by VladislavFitz** [comment]
Hi @aplusm,
Thank you for reaching out. 
Did you call `filterState.notifyChange()` after applying the filter?

**Comment by aplusm** [comment]
Hi,

Yes, i did call `filterState.notifyChange()` but it changes nothing.

I think the issue is related to Float precision: A timestamp, as the current value _1581008937_ cannot be represented exactly by Float precision. 
If i change the filter value to a lower one (that can be represented **exactly** by a Float, the issue disappears.

**Comment by aplusm** [comment]
More precisely, it occurs as soon as the float is displayed with scientific notation

**Comment by VladislavFitz** [comment]
Thanks for reporting this. We are working on the fix.

**Comment by aplusm** [comment]
Hi @VladislavFitz,

Do you have an ETA of the bug fix ?

**Comment by VladislavFitz** [comment]
Hi @aplusm 
The issue should be fixed in [this branch](https://github.com/algolia/instantsearch-core-swift/tree/fix/numeric-filter-double-precision) of the InstantSearch Core library. I haven't tested it properly yet. 
Could you add this branch to dependencies of your project and check if it solves the problem for you?

**Comment by aplusm** [comment]
Thank you,

I've tested and there is the following issue:

`Float80' is unavailable: Float80 is only available on non-Windows x86 targets.`

**Comment by VladislavFitz** [comment]
I see, I've just pushed a fix for that. Could you try one more time?

**Comment by aplusm** [comment]
It's working now.

**Comment by VladislavFitz** [comment]
Thanks a lot for testing. The patch will be released tomorrow at the latest.

**Comment by VladislavFitz** [comment]
The patch 6.5.3 of InstantSearch Core have been released.
